name: commit[Bot]🤖

on:

  push:
    branches:
      - master
      
  schedule:
  - cron: "*/10 * * * *" #adding cron job

  workflow_dispatch:

jobs:
  auto_commit:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2      
        with:
         persist-credentials: false
         fetch-depth: 0

      - name: Modify last update
        run: |
          original = `curl "https://raw.githubusercontent.com/manho30/all-green-commit/master/LAST_UPDATED"`
          d =`date '+%a %d %b %Y at %H:%M:%S'`
          echo "${original}\n{$d}\n" > LAST_UPDATED
          
      - name: Commit changes
        run: |
          git config --local user.email "manhochan30@gmail.com"
          git config --local user.name "manho30"
          git add -A
          
          
          git commit -m "🤖[bot] commit ✔️ "
          
      - name: GitHub Push
        uses: ad-m/github-push-action@v0.6.0
        with:
          force: true
          directory: "."
          github_token: ${{ secrets.GITHUB_TOKEN }}
