name: Squash and Merge PRs and Delete Branch

on:
  pull_request:
    types: [closed]
  workflow_dispatch:

jobs:
  merge-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.name "manho30"
          git config --global user.email "manhochan30@gmail.com"

      - name: Squash and merge
        run: |
          git merge --squash ${{ github.event.pull_request.head.sha }}
          git commit -m "${{ github.event.pull_request.title }}"
          git push

      - name: Delete branch
        if: github.event.pull_request.merged == true
        run: |
          git push origin --delete ${{ github.event.pull_request.head.ref }}
          curl -H "Authorization: token ${{ secrets.GITHUB_TOKEN }}" -X DELETE ${{ github.event.pull_request.url }}

