name: Squash and Merge PRs

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  merge-pr:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Git user
        run: |
          git config --global user.name "manho30"
          git config --global user.email "manho30@users.noreply.github.com"

      - name: Squash and merge
        run: |
          git merge --squash ${{ github.event.pull_request.head.sha }}
          git commit -m "${{ github.event.pull_request.title }}"
          git push

